FROM ws2811-builder:latest as lib_builder

FROM golang:1.21.5 as builder

COPY --from=lib_builder /usr/local/lib/libws2811.a /usr/local/lib/
COPY --from=lib_builder /usr/local/include/ws2811 /usr/local/include/ws2811

WORKDIR /app

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -o /arena-nerf

FROM gcr.io/distroless/static-debian12

COPY --from=builder /arena-nerf /

ENTRYPOINT ["/arena-nerf"]
