variables:
  CI_IMAGE_REPO: "$CI_REGISTRY_IMAGE"
  CY_IMAGE_REGISTRY: "containeryard.evoforge.org"
  CY_IMAGE_REPO: "${CY_IMAGE_REGISTRY}/sonicstorm/infrastructure/compass"

build:image:
  image: alpinelinux/docker-cli
  stage: build
  script:
    - apk add --no-cache git bash make
    - ./build.sh "$CI_IMAGE_REPO" "$IMAGE_TAG"
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker image push $CI_IMAGE_REPO:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        IMAGE_TAG: $CI_COMMIT_SHA
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG

deploy:image:
  image: alpinelinux/docker-cli
  stage: deploy
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker image pull $CI_IMAGE_REPO:$IMAGE_TAG
    - docker tag $CI_IMAGE_REPO:$IMAGE_TAG $CY_IMAGE_REPO:$IMAGE_TAG
    - echo $ORCHESTRATION_CY_PASSWORD | docker login -u $ORCHESTRATION_CY_USERNAME --password-stdin $CY_IMAGE_REGISTRY
    - docker image push $CY_IMAGE_REPO:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: $CI_COMMIT_TAG