FROM node:21-alpine3.18

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

ENV HOST=0.0.0.0
EXPOSE 8080
CMD ["npm", "run", "dev", "--host", "0.0.0.0"]
